function datestring=get_timestamp;
        dateoflog = fix(clock);
        datestring=sprintf('%s%s%s%s%s%s',...
            num2str(dateoflog(1)),...
            num2str(dateoflog(2)),...
            num2str(dateoflog(3)),...
            num2str(dateoflog(4)),...
            num2str(dateoflog(5)),...
            num2str(dateoflog(6)));